#!/usr/bin/env python3
"""
Generate in-site "news" pages for Helen's Bourne Enterprise journalism, and
regenerate the JOURNALISM list in data.js, from the plain-text clippings in
articles/.

Each articles/*.txt file has four header lines (Title, Author, Date, URL),
a blank line, then the article body as one paragraph per line (this is how
collect_articles_v2.py writes them).

Run from the repo root:   python3 tools/gen_news.py
Outputs:                  news/<slug>.html   (one per clipping)
                           the JOURNALISM array inside data.js, rewritten
                           in place between its start/end markers.

Requires nothing beyond the standard library.
"""

import glob
import html
import json
import os
import re
import sys
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "articles")
OUT = os.path.join(ROOT, "news")
DATA_JS = os.path.join(ROOT, "data.js")
PUBLICATION = "The Bourne Enterprise"

MARK_START = "// AUTO-GENERATED BY tools/gen_news.py: entries below are rebuilt from articles/*.txt. Do not hand-edit; re-run the script instead."
MARK_END = "// END AUTO-GENERATED"

# Article titles pinned to the top of the newsroom, in this order. They stay on
# top even when older than the newest clips, and are marked as pinned. Each must
# match the "Title:" header of a file in articles/ exactly.
PINNED = [
    "Barnstable County Entomologist Breaks Down Tick Risks, Offers Safety Tips",
    "Nancy Jack Todd Leaves Legacy Of Ecological Sustainability",
]

# ------------------------------------------------------------------ helpers ---
def slugify(title):
    s = title.replace("’", "'")
    s = s.replace("'", "")
    s = re.sub(r"[^\w\s-]", "", s)
    s = s.lower()
    s = re.sub(r"[\s_]+", "-", s).strip("-")
    return s or "article"

def title_word(w):
    w = w.lower()
    return re.sub(r"(^|['’-])([a-z])", lambda m: m.group(1) + m.group(2).upper(), w)

def format_name(name):
    return " ".join(title_word(w) for w in name.split(" ") if w)

def split_names(author):
    parts = re.split(r",\s*", author.strip())
    last = parts[-1].split(" and ")
    return [p.strip() for p in (parts[:-1] + last) if p.strip()]

def join_names(names):
    if not names:
        return ""
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return names[0] + " and " + names[1]
    return ", ".join(names[:-1]) + " and " + names[-1]

def parse_article(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    lines = text.split("\n")
    fields = {}
    i = 0
    for i, ln in enumerate(lines):
        m = re.match(r"^(Title|Author|Date|URL):\s*(.*)$", ln)
        if not m:
            break
        fields[m.group(1)] = m.group(2).strip()
    body_start = i
    while body_start < len(lines) and lines[body_start].strip() != "":
        body_start += 1
    body_start += 1
    paragraphs = [ln.strip() for ln in lines[body_start:] if ln.strip()]
    return fields, paragraphs

# --------------------------------------------------------------- templates ---
PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} &middot; Helen Sievert</title>
<meta name="description" content="{descr}">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;0,700;0,800;0,900;1,500;1,700&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,500;0,8..60,600;1,8..60,400&family=Oswald:wght@300;400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../styles.css">
</head>
<body>

<div id="site-header"></div>

<main class="wrap article">
  <div class="article-head">
    <span class="kicker">{publication}</span>
    <h1>{title}</h1>
    <p class="venue">By {byline}</p>
    <div class="article-meta">{date}</div>
  </div>

  <article class="prose">
{body}
  </article>

  <div class="article-foot">
    <a class="btn solid" href="{url}" target="_blank" rel="noopener">Originally published by The Bourne Enterprise</a>
    <a class="btn" href="../newsroom.html">&larr; All newsroom</a>
  </div>
</main>

<div id="site-footer"></div>

<script>window.SITE_BASE="../";window.SITE_PAGE="newsroom";</script>
<script src="../site.js"></script>
</body>
</html>
"""

def build_page(slug, title, byline, date_disp, url, paragraphs, nl="\n"):
    body = "\n".join("<p>%s</p>" % html.escape(p) for p in paragraphs)
    descr = html.escape("Journalism by Helen Sievert for The Bourne Enterprise. %s" % title)
    page = PAGE.format(
        title=html.escape(title),
        descr=descr,
        publication=html.escape(PUBLICATION),
        byline=html.escape(byline),
        date=html.escape(date_disp),
        url=html.escape(url, quote=True),
        body=body,
    )
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, slug + ".html"), "w", encoding="utf-8", newline="") as f:
        f.write(page.replace("\n", nl))

def js_entry(entry):
    lines = ["  {"]
    lines.append("    title: %s," % json.dumps(entry["title"], ensure_ascii=False))
    if entry.get("pinned"):
        lines.append("    pinned: true,")
    lines.append("    publication: %s," % json.dumps(PUBLICATION, ensure_ascii=False))
    lines.append("    date: %s," % json.dumps(entry["date"], ensure_ascii=False))
    if entry.get("coauthors"):
        lines.append("    coauthors: %s," % json.dumps(entry["coauthors"], ensure_ascii=False))
    lines.append("    url: %s," % json.dumps(entry["url"], ensure_ascii=False))
    lines.append("    page: %s," % json.dumps(entry["page"], ensure_ascii=False))
    lines.append("    blurb: %s" % json.dumps(entry["blurb"], ensure_ascii=False))
    lines.append("  }")
    return "\n".join(lines)

def main():
    paths = sorted(glob.glob(os.path.join(SRC, "*.txt")))
    if not paths:
        print("No articles found in %s" % SRC, file=sys.stderr)
        sys.exit(1)

    # Preserve the newline style already used in data.js (and the news pages),
    # so regenerating does not rewrite every line just to flip CRLF and LF.
    with open(DATA_JS, "rb") as f:
        NL = "\r\n" if b"\r\n" in f.read() else "\n"

    seen_slugs = set()
    entries = []

    for path in paths:
        fields, paragraphs = parse_article(path)
        for req in ("Title", "Author", "Date", "URL"):
            if req not in fields:
                raise RuntimeError("%s missing %s header" % (path, req))
        title = fields["Title"]
        author = fields["Author"]
        url = fields["URL"]
        dt = datetime.fromisoformat(fields["Date"])
        date_disp = "%s %d, %d" % (dt.strftime("%B"), dt.day, dt.year)

        slug = base_slug = slugify(title)
        n = 2
        while slug in seen_slugs:
            slug = "%s-%d" % (base_slug, n)
            n += 1
        seen_slugs.add(slug)

        names = [format_name(n) for n in split_names(author)]
        byline = join_names(names)
        others = [n for n in names if n.lower() != "helen sievert"]
        coauthors = join_names(others) if others else None

        build_page(slug, title, byline, date_disp, url, paragraphs, NL)

        entries.append({
            "sort_key": dt,
            "title": title,
            "date": date_disp,
            "coauthors": coauthors,
            "url": url,
            "page": "news/%s.html" % slug,
            "blurb": paragraphs[0] if paragraphs else "",
        })

    entries.sort(key=lambda e: e["sort_key"], reverse=True)

    # Pin the configured titles to the top, in PINNED order, and flag them.
    known = {e["title"] for e in entries}
    for missing in [t for t in PINNED if t not in known]:
        print("WARNING: pinned title not found in articles: %r" % missing, file=sys.stderr)
    rank = {t: i for i, t in enumerate(PINNED)}
    for e in entries:
        e["pinned"] = e["title"] in rank
    entries.sort(key=lambda e: rank.get(e["title"], len(PINNED)))

    array_body = ",\n\n".join(js_entry(e) for e in entries)
    new_block = (
        "window.JOURNALISM = [\n\n"
        + MARK_START + "\n\n"
        + array_body + "\n\n"
        + MARK_END + "\n\n"
        + "];"
    ).replace("\n", NL)

    with open(DATA_JS, encoding="utf-8", newline="") as f:
        data = f.read()

    pattern = re.compile(r"window\.JOURNALISM\s*=\s*\[.*?\];", re.DOTALL)
    if not pattern.search(data):
        raise RuntimeError("Could not find window.JOURNALISM array in data.js")
    data = pattern.sub(lambda m: new_block, data, count=1)

    with open(DATA_JS, "w", encoding="utf-8", newline="") as f:
        f.write(data)

    print("Generated %d news pages in %s" % (len(entries), OUT))
    print("Rewrote JOURNALISM array in %s" % DATA_JS)

if __name__ == "__main__":
    main()
